const questions = [
	// Grappig & random
	"Heb je vandaag al gelachen?",
	"Zou je een week zonder telefoon kunnen?",
	"Praat je soms tegen jezelf?",
	"Heb je ooit gedaan alsof je iemand niet zag?",
	"Heb je ooit een bericht verwijderd omdat je spijt had?",
	"Heb je ooit naar een gesprek geluisterd terwijl je niet mee mocht luisteren?",
	"Heb je ooit gelogen om ergens onderuit te komen?",
	"Heb je ooit gedaan alsof je ziek was?",
	"Heb je ooit per ongeluk iets gênants naar de verkeerde persoon gestuurd?",
	"Heb je ooit midden in de nacht nog wakker gelegen zonder reden?",
	"Zou je een dag zonder internet kunnen?",
	"Heb je ooit een hele dag in je pyjama gezeten?",
	"Heb je ooit tegen een deur of muur gepraat alsof die kon antwoorden?",
	"Heb je ooit iets gezocht wat letterlijk voor je lag?",
	"Heb je ooit moeten lachen op een moment dat het absoluut niet mocht?",
	"Heb je ooit gedaan alsof je een grap snapte terwijl dat niet zo was?",
	"Heb je ooit een geheim verklapt?",
	"Heb je ooit expres een bericht genegeerd?",
	"Heb je ooit een smoes verzonnen om niet ergens heen te gaan?",
	"Heb je ooit iets kapotgemaakt en het niet verteld?",
	// 🎮 Gaming
	"Speel je elke week games?",
	"Heb je ooit langer dan 5 uur achter elkaar gegamed?",
	"Ben je ooit boos geworden door een game?",
	"Heb je ooit een controller of toetsenbord bijna gesloopt van woede?",
	"Heb je ooit een ragequit gedaan?",
	"Heb je ooit een game gekocht en hem bijna nooit gespeeld?",
	"Heb je ooit een game uitgespeeld?",
	"Speel je liever met vrienden dan alleen?",
	"Heb je ooit tot laat in de nacht gegamed?",
	"Heb je ooit gelogen over hoeveel uur je hebt gegamed?",
	"Heb je ooit een game verwijderd omdat je er slecht in was?",
	"Heb je ooit een game opnieuw geïnstalleerd nadat je hem had verwijderd?",
	"Heb je ooit een overwinning gevierd alsof je een kampioenschap had gewonnen?",
	"Heb je ooit iemand uitgescholden tijdens het gamen?",
	"Heb je ooit een potje verloren door een domme fout?",
	"Heb je ooit een game alleen gekocht omdat je vrienden hem speelden?",
	"Heb je ooit een game gespeeld die je eigenlijk niet leuk vond?",
	"Heb je ooit een nacht doorgehaald om te gamen?",
	"Vind je Minecraft leuk?",
	"Vind je Roblox leuk?",
	// 📱 Internet & Discord
	"Ben je dagelijks op Discord?",
	"Heb je ooit urenlang door TikTok gescrold?",
	"Heb je ooit een bericht 10 keer opnieuw gelezen voordat je het stuurde?",
	"Heb je ooit per ongeluk een verkeerde emoji gestuurd?",
	"Heb je ooit een bericht verwijderd omdat niemand reageerde?",
	"Zit je in meer dan 5 Discord-servers?",
	"Heb je ooit een Discord-server verlaten en later weer gejoined?",
	"Heb je ooit iemand gemute omdat die irritant was?",
	"Heb je ooit iemand geblokkeerd?",
	"Heb je ooit je profielfoto meer dan 5 keer veranderd?",
	"Heb je ooit je Discord-status expres op iets grappigs gezet?",
	"Heb je ooit een hele nacht online gezeten?",
	"Heb je ooit een bericht gestuurd en meteen spijt gehad?",
	"Heb je ooit per ongeluk in het verkeerde kanaal gestuurd?",
	"Heb je ooit een voicechat verlaten omdat het te chaotisch werd?",
	"Heb je ooit een inside joke gehad met iemand van Discord?",
	"Heb je ooit iemand van Discord in het echt ontmoet?",
	"Heb je ooit een online vriend(in) gemaakt?",
	"Heb je ooit iemand online vertrouwd die je eigenlijk niet kende?",
	"Open je Discord meestal meteen als je je telefoon/computer aanzet?",
	// 🏫 School
	"Vind je school meestal leuk?",
	"Heb je ooit je huiswerk vergeten?",
	"Heb je ooit je huiswerk pas vlak voor de les gemaakt?",
	"Heb je ooit een toets vergeten?",
	"Heb je ooit afgekeken?",
	"Heb je ooit gedaan alsof je het antwoord wist?",
	"Heb je ooit te laat een opdracht ingeleverd?",
	"Heb je ooit bijna in slaap gevallen tijdens een les?",
	"Heb je ooit gelachen tijdens een serieus moment?",
	"Heb je ooit een docent per ongeluk bij de verkeerde naam genoemd?",
	"Vind je pauzes leuker dan lessen?",
	"Zou je liever een dag extra vrij hebben dan een kortere schooldag?",
	"Heb je ooit je boeken thuis laten liggen?",
	"Heb je ooit een toets geleerd die uiteindelijk veel makkelijker was dan verwacht?",
	"Heb je ooit een toets gemaakt zonder te leren?",
	// 🍕 Eten & dagelijks leven
	"Eet je graag pizza?",
	"Hou je van friet?",
	"Hou je van chocolade?",
	"Drink je graag cola?",
	"Eet je soms 's avonds nog iets terwijl je eigenlijk niet honger hebt?",
	"Heb je ooit ontbijt overgeslagen?",
	"Heb je ooit eten besteld terwijl er thuis eten was?",
	"Heb je ooit iets gegeten dat op de grond was gevallen?",
	"Heb je ooit een hele zak chips in één keer opgegeten?",
	"Hou je van pittig eten?",
	"Eet je soms snacks als je je verveelt?",
	"Heb je ooit iets gegeten terwijl je wist dat het eigenlijk over datum was?",
	"Zou je pizza als ontbijt eten?",
	"Zou je een week lang hetzelfde eten?",
	"Kun je koken zonder recept?",
	// 🔥 Persoonlijk / leuke discussie
	"Ben je een ochtendmens?",
	"Ben je vaak te laat?",
	"Ben je snel afgeleid?",
	"Ben je vaak je telefoon kwijt?",
	"Kun je goed geheimen bewaren?",
	"Zou je jezelf introvert noemen?",
	"Zou je jezelf grappig noemen?",
	"Ben je snel zenuwachtig?",
	"Zou je zonder problemen een dag alleen thuis kunnen zijn?",
	"Vind je dit Discord-kanaal leuk? 👀",
];

const dailyPollQuestions = questions.map(question => ({
	question,
	answers: ['Ja', 'Nee'],
}));

module.exports = { dailyPollQuestions };
