const topics = [
	'Ontbijt op bed', 'Een kamer met zeezicht', 'Een late check-out', 'Een privézwembad',
	'Een open haard', 'Een kingsize bed', 'Een regendouche', 'Een balkon',
	'Roomservice', 'Een hotelbioscoop', 'Een spelletjesavond', 'Een wellnessdag',
	'Een verrassingsreis', 'Een stedentrip', 'Een strandvakantie', 'Een berghut',
	'Kamperen onder de sterren', 'Een roadtrip', 'Een cruise', 'Een pretparkweekend',
	'Altijd zomer', 'Altijd winter', 'Nooit meer files', 'Gratis reizen',
	'Kunnen vliegen', 'Onzichtbaar zijn', 'Gedachten lezen', 'De tijd stilzetten',
	'Een jaar zonder sociale media', 'Een maand zonder telefoon', 'Thuiswerken', 'Een vierdaagse werkweek',
	'Vroeg opstaan', 'Laat opblijven', 'Een powernap', 'Uitslapen op zondag',
	'Koffie in de ochtend', 'Thee in de avond', 'Ontbijt als avondeten', 'Pizza als ontbijt',
	'Zoet popcorn', 'Zoute popcorn', 'Ananas op pizza', 'Friet met mayonaise',
	'Zelf koken', 'Uit eten gaan', 'Een uitgebreid buffet', 'Een verrassingsmenu',
	'Een hond als huisdier', 'Een kat als huisdier', 'Een papegaai als huisdier', 'Geen huisdieren',
	'Een boek lezen', 'Een film kijken', 'Een serie bingen', 'Een podcast luisteren',
	'Live muziek', 'Een comedyshow', 'Een museumbezoek', 'Een festival',
	'Een bordspel', 'Een videogame', 'Een escape room', 'Een pubquiz',
	'Voetbal kijken', 'Zelf sporten', 'Een lange wandeling', 'Een fietstocht',
	'Een ochtendtraining', 'Een avondtraining', 'Yoga', 'Krachttraining',
	'Een zonnige dag', 'Een regenachtige dag binnen', 'Sneeuw met kerst', 'Een onweersbui bekijken',
	'Wonen in de stad', 'Wonen op het platteland', 'Wonen aan zee', 'Wonen in het buitenland',
	'Een klein gezellig huis', 'Een groot modern huis', 'Een tiny house', 'Een historisch pand',
	'Een verrassingsfeest', 'Een rustig diner', 'Een groot verjaardagsfeest', 'Je verjaardag overslaan',
	'Cadeaus geven', 'Cadeaus krijgen', 'Een handgemaakt cadeau', 'Een belevenis cadeau',
	'Kerstmis', 'Oud en nieuw', 'Halloween', 'Koningsdag',
	'Lente', 'Zomer', 'Herfst', 'Winter',
	'Muziek tijdens het werken', 'Volledige stilte', 'Een drukke werkplek', 'Een eigen kantoor',
	'Een nieuwe taal leren', 'Een instrument leren', 'Leren koken', 'Leren fotograferen',
	'Een dag zonder plannen', 'Een volledig geplande dag', 'Spontaan op pad', 'Een weekend thuis',
	'Een papieren boek', 'Een e-reader', 'Een luisterboek', 'Een stripboek',
	'Een actiefilm', 'Een komedie', 'Een horrorfilm', 'Een documentaire',
	'Tijdreizen naar het verleden', 'Tijdreizen naar de toekomst', 'Naar de maan reizen', 'De diepzee verkennen',
	'Beroemd zijn', 'Heel rijk zijn', 'Heel wijs zijn', 'Altijd geluk hebben',
	'Een persoonlijke chef', 'Een persoonlijke chauffeur', 'Een schoonmaakhulp', 'Een reisplanner',
	'Nooit meer hoeven slapen', 'Nooit meer hoeven werken', 'Elke dag weekend', 'Elk jaar drie maanden vakantie',
	'Een wereld zonder reclame', 'Een wereld zonder spam', 'Een wereld zonder wachtwoorden', 'Een wereld zonder wekker',
	'Een dag als superheld', 'Een dag als filmster', 'Een dag als chef-kok', 'Een dag als astronaut',
	'Je favoriete lied op repeat', 'Elke dag nieuwe muziek', 'Alle concerten gratis', 'Zelf perfect kunnen zingen',
	'Een fotoalbum maken', 'Een dagboek bijhouden', 'Video’s van reizen maken', 'Souvenirs verzamelen',
	'Een verrassend einde', 'Een gelukkig einde', 'Een open einde', 'Een vervolg op het verhaal',
	'Online winkelen', 'Winkelen in de stad', 'Tweedehands kopen', 'Alles lokaal kopen',
	'Contant betalen', 'Contactloos betalen', 'Een maandbudget maken', 'Spontaan iets kopen',
	'Een teamproject', 'Alleen werken', 'De leiding nemen', 'Iemand anders laten kiezen',
	'Een eerlijk compliment', 'Een goede grap', 'Een lang gesprek', 'Samen stil kunnen zijn',
	'Een nieuwe vriend ontmoeten', 'Een oude vriend terugzien', 'Een familiefeest', 'Tijd voor jezelf',
	'Een zonsopkomst bekijken', 'Een zonsondergang bekijken', 'Sterren kijken', 'Een nachtelijke wandeling',
	'Een geheime tuin', 'Een verborgen bibliotheek', 'Een verlaten kasteel', 'Een tropisch eiland',
	'Een draak als vriend', 'Een pratend huisdier', 'Een eigen robot', 'Een magische deur',
	'Alles altijd onthouden', 'Elke taal spreken', 'Perfect kunnen tekenen', 'Elk instrument bespelen',
	'Een dag zonder verplichtingen', 'Een onverwacht vrije middag', 'Een extra vakantiedag', 'Een rustige maandagochtend',
	'Een picknick in het park', 'Een barbecue met vrienden', 'Een ontbijt bij zonsopkomst', 'Een diner bij kaarslicht',
];

const dailyPollQuestions = topics.map(topic => ({
	question: `${topic}: lijkt je dat leuk?`,
	answers: ['Ja, absoluut!', 'Misschien', 'Nee, liever niet'],
}));

module.exports = { dailyPollQuestions };
